apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lifting-logbook-web.fullname" . }}-config
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  PORT: {{ .Values.env.PORT | quote }}
  API_URL: {{ .Values.env.API_URL | quote }}
