apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lifting-logbook-api.fullname" . }}-config
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  PORT: {{ .Values.env.PORT | quote }}
  KMS_KEY_NAME: {{ .Values.gcp.kmsKeyName | quote }}
