apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}
  labels:
    app: {{ include "otel-collector.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "otel-collector.fullname" . }}
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
